### STAGE 1: Build ###

FROM node:16-alpine AS build
WORKDIR /usr/src/app
COPY . .
RUN npm ci
RUN npm run build:storybook:front-dynamic-forms

### STAGE 2: Serve ###

FROM nginx:1.17.1-alpine
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/storybook/front-dynamic-forms /usr/share/nginx/html
EXPOSE 8080
